"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { buttonPrimary, buttonSecondary, inputClass, labelClass } from "@/components/ui";

type Company = { companyName: string; tin: string; bankName: string; bankAccount: string; defaultTerms: string; defaultInvoiceTitle: string; logoPath: string };
type InvoiceType = { id: number; name: string; prefix: string; nextNumber: number; padding: number; documentTitle: string };

export function SettingsPanel({ initialCompany, initialTypes }: { initialCompany: Company; initialTypes: InvoiceType[] }) {
  const router = useRouter();
  const [company, setCompany] = useState(initialCompany);
  const [types, setTypes] = useState(initialTypes);
  const [newType, setNewType] = useState({ name: "", prefix: "", nextNumber: 1, padding: 4, documentTitle: "Sales Invoice" });
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);

  async function saveCompany(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setMessage("");
    const res = await fetch("/api/settings/company", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(company) }); const data = await res.json();
    setBusy(false); setMessage(res.ok ? "Company settings saved." : data.error || "Unable to save settings."); if (res.ok) router.refresh();
  }
  async function saveType(type: InvoiceType) {
    setBusy(true); setMessage(""); const res = await fetch(`/api/invoice-types/${type.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(type) }); const data = await res.json(); setBusy(false); setMessage(res.ok ? `${type.name} updated.` : data.error || "Unable to update invoice type."); if (res.ok) router.refresh();
  }
  async function addType(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setMessage(""); const res = await fetch("/api/invoice-types", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(newType) }); const data = await res.json(); setBusy(false); if (!res.ok) return setMessage(data.error || "Unable to create invoice type."); setTypes((all) => [...all, data]); setNewType({ name: "", prefix: "", nextNumber: 1, padding: 4, documentTitle: "Sales Invoice" }); setMessage("Invoice type added."); router.refresh();
  }
  async function backup() {
    setBusy(true); setMessage(""); const res = await fetch("/api/settings/backup", { method: "POST" }); const data = await res.json(); setBusy(false); setMessage(res.ok ? `Backup created: data/backups/${data.fileName}` : data.error || "Backup failed.");
  }

  return <div className="space-y-6">
    {message ? <div className="rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm shadow-sm">{message}</div> : null}
    <form onSubmit={saveCompany} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center gap-4"><img src={company.logoPath} alt="Company logo" className="h-20 w-auto object-contain" /><div><h2 className="font-semibold">Company & Invoice Defaults</h2><p className="mt-1 text-sm text-slate-500">These values are printed on generated customer invoices. Replace public/company-logo.png if the logo changes.</p></div></div><div className="grid gap-4 md:grid-cols-2"><label><span className={labelClass}>Company Name</span><input className={inputClass} value={company.companyName} onChange={(e) => setCompany({ ...company, companyName: e.target.value })} /></label><label><span className={labelClass}>TIN</span><input className={inputClass} value={company.tin} onChange={(e) => setCompany({ ...company, tin: e.target.value })} /></label><label><span className={labelClass}>Bank Name</span><input className={inputClass} value={company.bankName} onChange={(e) => setCompany({ ...company, bankName: e.target.value })} /></label><label><span className={labelClass}>Bank Account</span><input className={inputClass} value={company.bankAccount} onChange={(e) => setCompany({ ...company, bankAccount: e.target.value })} /></label><label><span className={labelClass}>Default Terms</span><input className={inputClass} value={company.defaultTerms} onChange={(e) => setCompany({ ...company, defaultTerms: e.target.value })} /></label><label><span className={labelClass}>Default Invoice Title</span><input className={inputClass} value={company.defaultInvoiceTitle} onChange={(e) => setCompany({ ...company, defaultInvoiceTitle: e.target.value })} /></label></div><button className={`${buttonPrimary} mt-4`} disabled={busy}>Save Company Settings</button></form>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Invoice Types & Sequences</h2><p className="mt-1 text-sm text-slate-500">Each type has an independent sequence. Be careful when lowering Next Number because an existing invoice number cannot be reused.</p><div className="mt-4 space-y-3">{types.map((type, index) => <div key={type.id} className="grid gap-3 rounded-lg border border-slate-200 p-4 md:grid-cols-[1.2fr_.7fr_.8fr_.6fr_1.4fr_auto] md:items-end"><label><span className={labelClass}>Name</span><input className={inputClass} value={type.name} onChange={(e) => setTypes((all) => all.map((t, i) => i === index ? { ...t, name: e.target.value } : t))} /></label><label><span className={labelClass}>Prefix</span><input className={inputClass} value={type.prefix} onChange={(e) => setTypes((all) => all.map((t, i) => i === index ? { ...t, prefix: e.target.value.toUpperCase() } : t))} /></label><label><span className={labelClass}>Next No.</span><input className={inputClass} type="number" min="1" value={type.nextNumber} onChange={(e) => setTypes((all) => all.map((t, i) => i === index ? { ...t, nextNumber: Number(e.target.value) } : t))} /></label><label><span className={labelClass}>Padding</span><input className={inputClass} type="number" min="1" max="10" value={type.padding} onChange={(e) => setTypes((all) => all.map((t, i) => i === index ? { ...t, padding: Number(e.target.value) } : t))} /></label><label><span className={labelClass}>Document Title</span><input className={inputClass} value={type.documentTitle} onChange={(e) => setTypes((all) => all.map((t, i) => i === index ? { ...t, documentTitle: e.target.value } : t))} /></label><button type="button" className={buttonSecondary} onClick={() => saveType(type)} disabled={busy}>Save</button></div>)}</div></section>
    <form onSubmit={addType} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Add Invoice Type</h2><div className="mt-4 grid gap-3 md:grid-cols-5"><label><span className={labelClass}>Name</span><input className={inputClass} value={newType.name} onChange={(e) => setNewType({ ...newType, name: e.target.value })} required /></label><label><span className={labelClass}>Prefix</span><input className={inputClass} value={newType.prefix} onChange={(e) => setNewType({ ...newType, prefix: e.target.value.toUpperCase() })} required /></label><label><span className={labelClass}>Start No.</span><input className={inputClass} type="number" min="1" value={newType.nextNumber} onChange={(e) => setNewType({ ...newType, nextNumber: Number(e.target.value) })} required /></label><label><span className={labelClass}>Padding</span><input className={inputClass} type="number" min="1" max="10" value={newType.padding} onChange={(e) => setNewType({ ...newType, padding: Number(e.target.value) })} required /></label><label><span className={labelClass}>Document Title</span><input className={inputClass} value={newType.documentTitle} onChange={(e) => setNewType({ ...newType, documentTitle: e.target.value })} required /></label></div><button className={`${buttonPrimary} mt-4`} disabled={busy}>Add Invoice Type</button></form>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Database Backup</h2><p className="mt-1 text-sm text-slate-500">Creates a timestamped copy of the local SQLite database inside data/backups.</p><button className={`${buttonSecondary} mt-4`} type="button" onClick={backup} disabled={busy}>Create Backup Now</button></section>
  </div>;
}
